### ISSUE TITLE
compatibility with latest version of TensorFlow

### ISSUE THREAD

**Issue by tommycarstensen** [johanndejong/VaDER#11]
VaDER is no longer compatible with the latest version of TensorFlow. Specifically it throws this error:

from utils import positional_encoding, scaled_dot_product_attention
ImportError: cannot import name 'positional_encoding' from 'utils' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/utils/__init__.py)

**Comment by johanndejong** [comment]
Seems not to be a version issue, but a problem with your code not being able to find the functions positional_encoding, scaled_dot_product_attention in the file utils.py (provided as part of the vader code). 

Re-organized the code a bit so it can be installed with pip. Should be easier for you to run it now.
